language: haskell
ghc: 7.10.3

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.cabal/packages

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
            - hvr-ghc
        packages:
            - g++-4.9
            - gcc-4.9
            - binutils
            - cmake
            - mono-gmcs
            - phantomjs
            - cabal-install-1.22

install: true
script: travis/build-and-test.sh

notifications:
    email:
        on_success: always
    on_failure: always

