language: haskell
ghc: 7.8

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
        packages:
            - g++-4.9
            - gcc-4.9
            - binutils
            - cmake
            - mono-gmcs
            - phantomjs

install: true
script: travis/build-and-test.sh

notifications:
    email:
        on_success: always
    on_failure: always

